### ISSUE TITLE
IHEX_FLAG_ADDRESS_OVERFLOW is cleared without writing Extended Linear Address

### ISSUE THREAD

**Issue by tylerjsmith** [arkku/ihex#5]
I have found a situation where if I have two logical blocks of data that happen to be adjacent on the 64kB address boundary, the Extended Linear Address header is never written.

It can be mimicked by the following:
ihex_write_at_address(&state, 0xFFF0);
ihex_write_bytes(&state, dataBuffer, 0x10);
ihex_write_at_address(&state, 0x10000);
ihex_write_bytes(&state, dataBuffer, 0x10);

The problem is in the ihex_write_at_address() function. It will flush the previous existing data, then compare the ihex->address upper bytes to the new requested address upperbytes. Both are now the same, since ihex_write_data() has incremented ihex->address.

Would this be an acceptable change:
```
void
ihex_write_at_address (struct ihex_state *ihex, ihex_address_t address) {
    if (ihex->length) {
        // flush any existing data
        ihex_write_data(ihex);
    }
    if (((ihex->address & ADDRESS_HIGH_MASK) != (address & ADDRESS_HIGH_MASK)) ||
        (ihex->address == (address & ADDRESS_HIGH_MASK)) ){
        ihex->flags |= IHEX_FLAG_ADDRESS_OVERFLOW;
    } else {
        ihex->flags &= ~IHEX_FLAG_ADDRESS_OVERFLOW;
    }
    ihex->address = address;
    ihex_set_output_line_length(ihex, ihex->line_length);
}
```

Here, we also check for the boundary condition where the ihex->address is the boundary address of the 64kB block of addresses we are changing to.

**Comment by arkku** [comment]
Hi, there is indeed a bug that the address overflow flag is cleared when setting the new address to the same page but before anything else has been written. Your fix does work, but I would reformulate it to "not clear" rather than "set" the flag, i.e.,:

```
void
ihex_write_at_address (struct ihex_state *ihex, ihex_address_t address) {
    if (ihex->length) {
        // flush any existing data
        ihex_write_data(ihex);
    }

    const ihex_address_t page = address & ADDRESS_HIGH_MASK;
    if ((ihex->address & ADDRESS_HIGH_MASK) != page) {
        ihex->flags |= IHEX_FLAG_ADDRESS_OVERFLOW;
    } else if (ihex->address != page) {
        ihex->flags &= ~IHEX_FLAG_ADDRESS_OVERFLOW;
    }

    ihex->address = address;
    ihex_set_output_line_length(ihex, ihex->line_length);
}
```
